#!/usr/bin/bash

export JAVA_HOME='C:\jdk1.8.0_45'
export JBOSS_HOME='C:\jboss-eap-6.4-1'
#cd /c/jboss-eap-6.4-1/bin

read -sp ' Enter password for admin: ' passvar
echo

for x in $(cat servicenodes.txt)
do
    #echo $x
    echo "undeploying services using $x"
    (/c/jboss-eap-6.4-1/bin/jboss-cli.sh -c controller=$x command="undeploy evaas-batchprint-ear.ear") &
    (/c/jboss-eap-6.4-1/bin/jboss-cli.sh -c controller=$x command="undeploy evaas-dataexport-ear.ear") &
    (/c/jboss-eap-6.4-1/bin/jboss-cli.sh -c controller=$x command="undeploy evaas-mail-ear.ear") &
done 

wait

